apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: omniverse
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: apiserver

      - job_name: 'nexus-backend-metrics'
        scrape_port: 5003
        metrics_path: '/metrics'
        static_configs:
          - targets: ['nexus-backend-service.omniverse.svc.cluster.local:5003']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'nexus-backend'
